#!/usr/bin/env bash
# This script install nginx en virtual server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y upgrade

echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sudo sed -i '/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx start
